export {default as ArmasBlock} from './blocks/armas'
export {default as GuardasBlock} from './blocks/guardas'
export {default as ViaturasBlock} from './blocks/viaturas'
export {default as EquipamentosBlock} from './blocks/equipamentos'
export {default as RegistroDePontosBlock} from './blocks/registropontos'
export {default as BoletimSimplificadoBlock} from './blocks/boletimsimplificado'
export {default as BoletimDeOcorrenciaBlock} from './blocks/boletimdeocorrencia'
